---
abstract: 'RealVault, Remote (Integrated) XML Solution'
author:
  - 'Fayland Lam <fayland@gmail.com>'
build_requires:
  Test::More: 0.88
configure_requires:
  Module::Build::Tiny: 0.030
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.4, Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Business-RealEx
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Digest::SHA1: 0
  LWP::UserAgent: 0
  XML::Simple: 0
  perl: 5.008005
resources:
  bugtracker: https://github.com/fayland/p5-Business-RealEx/issues
  homepage: https://github.com/fayland/p5-Business-RealEx
  repository: https://github.com/fayland/p5-Business-RealEx.git
version: 0.02
